garan=int(input("Nhập số gà rán"))
hamburger=int(input("Nhập số Hamburger"))
cocacola=int(input("Nhập số cocacola"))
print("Chào mừng các bạn đến với nhà hàng thức ăn nhanh !")
print("Mời bạn nhập số lượng từng món ăn:")
print("Gà rán: ",garan)
print("Hamburger: ",hamburger)
print("Cocacola: ",cocacola)
print("Hóa đơn:")
print("Gà rán","30.000đ",garan)
print("Hamburger","25.000đ",hamburger)
print("Cocacola","10.000đ",cocacola)
print("Tổng:")
print("Gà rán",30000*garan+"đ")
print("Hamburger",25000*hamburger+"đ")
print("Cocacola",50000*cocacola+"đ")
print("Tổng trước thuế",garan+hamburger+cocacola+"đ")
print("Thuế( 5%)",(garan+hamburger+cocacola)*5/100+"đ")
print("Tổng sau thuế",(garan+hamburger+cocacola)+((garan+hamburger+cocacola)*5/100))
